name: Nuxt.js Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: |
          npm install
          npm uninstall @babel/preset-env
          npm install @babel/preset-env@7.12.13
        working-directory: ./src/web-nuxt
      - name: Build
        run: npm run build
        working-directory: ./src/web-nuxt
